### ISSUE TITLE
Move web site parts from matroska-specification to separate repository

### ISSUE THREAD

**Issue by mbunkus** [Matroska-Org/infrastructure#1]
This is the continuation of  cellar-wg/matroska-specification#386.

**Comment by mbunkus** [comment]
@robUx4 just a "heads-up/FYI" ping

Current state of the move: I've migrated all pages safe for the whole "Technical / Info" sub-tree. I plan to include the matroska-specification repository as a sub-module and let Jekyll generate the pages in one step.

I'll include more information on how to build & develop the pages soon. I'll also provide a live version somewhere soon.

For now, if you want to test what's there:

```
git clone …
cd infrastructure/website
jekyll serve --watch
```

**Comment by mbunkus** [comment]
The migration is mostly done. The top-level README.md has updated build instructions.

The web site is currently available at https://dev.matroska.org/

I plan on replacing the old one in a couple of days if no one objects. I won't just delete the old one, though; if there's need, we'll be able to resurrect it (temporarily).

**Comment by robUx4** [comment]
Sounds good to me. You may mention in the README in this repo the dev.matroska.org link. Is it updated automatically or manually ?

**Comment by mbunkus** [comment]
I planned on moving the content over to www.matroska.org later today, so there's no need for for dev link. But I can mention www.matroska.org in the repo's README.

At the moment it isn't automated — yet. I'm still thinking about whether or not I really want to automate it, seeing as several pages required manual intervention to make them work properly. But I likely will (automate it, that is).

Another thing I was going to talk to you about is hosting stuff on the Sourceforge project site vs. hosting on dl.matroska.org. For reasons the stuff you publish is on SF while the stuff I publish is on dl.matroska.org. Some of your stuff is even on dl.matroska.org, but only in outdated versions. I'd really like to unify this on dl.matroska.org and complete deprecate the SF's Matroska project site.

For that to work, though, you'll need read/write access to dl.matroska.org (which is only a file tree with automatic indexing by the web server, no web pages involved). Assuming you're OK with the general idea, I was planning on implementing that today or tomorrow so that you can upload stuff there on your own. Afterwards I'd like to go over the new www.matroska.org web site & migrate all the stuff it points to on SF to dl.matroska.org.

Does that sound good to you?

**Comment by mbunkus** [comment]
The Jekyll-based web site is now live at www.matroska.org

**Comment by robUx4** [comment]
What happened to the old content ? Is it still visible somewhere, at least as a static page ? I often used the old site to double check how things used to be defined. So as things keep on changing it would be good to still have a reference. It's not any webpage but the page that used to be the de-facto standard for a long time.
It's still available on the [Wayback Machine](https://web.archive.org/web/20200118083915/https://matroska.org/technical/specs/index.html) but I don't know how long they keep "minor" websites stored.

**Comment by mbunkus** [comment]
At the moment the old content isn't available publicly. I can certainly create static copies under a different domain, e.g. "old.matroska.org".

I'm not too happy about keeping old content publicly available, though. All it does is confuse people, especially when they just Google for stuff and end up on "old.matroska.org" — most people never look at the URL/address bar.

That being said, I can certainly make the old stuff require a login and give you credentials. That way you could still compare with the old content without having it publicly available, if that works for you.

**Comment by mbunkus** [comment]
Old content is now available but password-protected. You should have received an email by now with your credentials.

**Comment by mbunkus** [comment]
Looks like everything's done from my point of view (safe for moving stuff over from SourceForge, but that's not urgent).
